name: example
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.10.1

dependencies:
  path: ^1.9.0
  postgres: ^3.5.9
  sqlite3: ^3.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
