name: sqlc_gen_dart
description: A plugin for SQLC that generates Dart code from SQL queries.
version: 1.0.0
repository: https://github.com/tiagualvs/sqlc_gen_dart

topics:
  - orm
  - sql
  - database
  - sqlite
  - postgresql

executables:
  sqlc-gen-dart: sqlc_gen_dart

environment:
  sdk: ^3.10.0

dependencies:
  pluralize: ^0.0.8
  strings: ^4.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
